##################################################
# Name: shiftleft.yaml
# Description: Workflow for ShiftLeft Scanner
##################################################

##################################################
# NOTES:
#       This workflow integrates ShiftLeft SAST scan with GitHub's code scanning feature.
#       ShiftLeft Scan is a free open-source security tool for modern DevOps teams
#       Visit https://slscan.io/en/latest/integrations/code-scan for help
#
##################################################

name: ShiftLeft

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"

  schedule:
    - cron: "0 0 * * 0"

jobs:
  shiftleft:
    name: Run ShiftLeft

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          persist-credentials: true

      - id: shiftleft_scan
        name: ShiftLeft Scan
        uses: ShiftLeftSecurity/scan-action@v1.3.0
        env:
          WORKSPACE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true
        with:
          output: reports
          # Scan auto-detects the languages in your project.
          # type: credscan,go,depscan

      - id: shiftleft_results
        name: Shiftleft Results
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          tree reports
          REPORTS=$(find reports/ -type f | wc -l)
          if [ "${REPORTS:-0}" -gt 0 ];
          then
            echo '::set-output name=results::TRUE'
          else
            echo '::set-output name=results::FALSE'
          fi

      - id: shiftleft_upload_html
        name: Shiftleft Upload (HTML)
        uses: actions/upload-artifact@v1
        if: ${{ steps.shiftleft_results.outputs.results == 'TRUE' }}
        with:
          name: reports
          path: reports

      - id: shiftleft_upload
        name: Shiftleft Upload (Sarif)
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ steps.shiftleft_results.outputs.results == 'TRUE' }}
        with:
          sarif_file: reports
